### ISSUE TITLE
Include an env. var for auth. for registry e2e tests

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop-e2e#104]
Registry E2E tests are failing and we need to include loading up of a env. var. for bot account in playwright e2e tests steps of windows workflows:

Example of failures: https://github.com/containers/podman-desktop-e2e/actions/runs/7708761189
Wofklows to update: https://github.com/containers/podman-desktop-e2e/blob/main/.github/workflows/desktop-e2e-podman-windows-matrix.yaml#L152, https://github.com/containers/podman-desktop-e2e/blob/main/.github/workflows/podman-desktop-e2e-nightly-windows.yaml#L138, https://github.com/containers/podman-desktop-e2e/blob/main/.github/workflows/podman-desktop-e2e-windows.yaml#L136

**Comment by adrianriobo** [comment]
Can this be closed by #107 ?

**Comment by odockal** [comment]
Unfortunately no. There is still a problem. we need to make sure to propagate the secret inside the running container on the target host system. 
So we need to add this parameter to the pde2e-runner image (ie. registryKey) into windows [ps script](https://github.com/odockal/pde2e-runner/blob/main/lib/windows/runner.ps1#L25) and similarly in darwin's sh script. And then update it to be passed as an image's parameter in this [job](https://github.com/containers/podman-desktop-e2e/blob/main/.github/workflows/desktop-e2e-podman-windows-matrix.yaml#L165), also [here](https://github.com/containers/podman-desktop-e2e/blob/main/.github/workflows/podman-desktop-e2e-nightly-windows.yaml#L151) and [here](https://github.com/containers/podman-desktop-e2e/blob/main/.github/workflows/podman-desktop-e2e-windows.yaml#L149).

@adrianriobo not sure about how efiiciently we can hide the secret in this configuration?
