### ISSUE TITLE
Extend pde2e-podman image to Mac platform

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop-e2e#110]
Right now we have pde2e-podman image that is part of various workflows only running on windows. We need to extend it to a mac platform.

**Comment by adrianriobo** [comment]
Can you link here the issue / PR on you repo for this? ( Idem for others)?

**Comment by odockal** [comment]
@adrianriobo Kind of: https://github.com/odockal/pde2e-podman/commit/04c53d6d1ab3d3dda544fcfc4872bb76f5baca0b
