### ISSUE TITLE
Integrate Podman Desktop Playwright e2e tests into workflow testing Podman Installation using GOAX on windows

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop-e2e#16]

**Comment by adrianriobo** [comment]
Not sure about the recent commits

**Comment by adrianriobo** [comment]
yeah, not sure why the podman-desktop-e2e is in there...would not that break your execution? , also In my mind you  do not build podman-desktop within the target testing host but only run your playwright script.

So not really sure where the runner image of code is coming from I was checking your repo but it seems to be empty

**Comment by odockal** [comment]
@benoitf @adrianriobo 

> Not sure about the recent commits [5ff16fb](https://github.com/containers/podman-desktop-e2e/commit/5ff16fbe4a70b4a1506db6fabb2aa9deec83330a) and [afbfd6a](https://github.com/containers/podman-desktop-e2e/commit/afbfd6a36d7d59b61165f303fcdaf9df87f6e8d6) also from [comment](https://github.com/containers/podman-desktop-e2e/pull/18#pullrequestreview-1644461977) :
> 
> > hi, what's the difference with https://github.com/containers/podman-desktop-e2e/blob/main/.github/workflows/windows.yaml ?
> 
> > shouldn't it be merged in the same launch ?

I believe that we have two various workflows here:
Test that installs podman through podman desktop and then
1. Run podman desktop e2e (Playwright) tests with use of already installed podman
2. Run Podman e2e tests against podman installed by podman desktop

**Comment by benoitf** [comment]
but could we not run PlayWright tests on the same Windows machine ?
We don't need another run. I think once we have the machine, we should execute all the tests from there.


Also maybe PlayWright tests can be executed just after podman has been installed by the goax tests.

**Comment by odockal** [comment]
> but could we not run PlayWright tests on the same Windows machine ? We don't need another run. I think once we have the machine, we should execute all the tests from there.

We might consider that. I would be for doing this when we have both workflows stable.

> Also maybe PlayWright tests can be executed just after podman has been installed by the goax tests.

That is what is happening, right?Ifyou have in mind reusing the same instance of podman desktop, then we need to first solve some issues with playwright and electron -> https://github.com/containers/podman-desktop/issues/4127
