### ISSUE TITLE
Implement an option to choose a provider for podman machine in pde2e-runner image

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop-e2e#206]
Podman offers an option to use a particular provider for creating a podman machine. 

On windows:
* wsl (default)
* hyperv

On Mac:
* applehv/vfkit (default)
* libkrun

The provider setup happens inside `containers.conf` file which happens to be at `~/config/containers/` on Mac and at `~/AppData/` location on windows.

references and issues:

**Comment by adrianriobo** [comment]
I did something similar on the podman-backend setting a param on the tekton task and then make use of it within the scripts inside the image:

tekton task:

https://github.com/adrianriobo/podman-e2e/blob/main/tkn/task.yaml#L69

script:

https://github.com/adrianriobo/podman-e2e/blob/main/oci/lib/darwin/run.sh#L64

**Comment by odockal** [comment]
@adrianriobo good point, it could be a bit easier using env. vars.

**Comment by odockal** [comment]
Fixed by: https://github.com/odockal/pde2e-runner/commit/445647b05c917cf0ee6ada61d0658c88925cc03f and https://github.com/odockal/pde2e-runner/commit/8a31c49cad94dd656d0a47826fed50e600818213
