### ISSUE TITLE
OpenShift pipelines are failing due to missing file

### ISSUE THREAD

**Issue by danivilla9** [containers/podman-desktop-e2e#258]
Currently [the OpenShift pipelines are failing to run](https://console-openshift-console.apps.gpc.ocp-hub.prod.psi.redhat.com/dev-pipelines/ns/devtoolsqe--pipeline), and almost all of them share this error message:
```
cp: cannot stat '/opt/storage/284115207/qe-results/*.xml': No such file or directory
	zip warning: name not matched: *.xml

zip error: Nothing to do! (pde2e-podman-nightly-applehv-5.2.0-dev-darwin-arm64-14.5.1.zip)
curl: (26) Failed to open/read local data from file/application
```

**Comment by odockal** [comment]
Seems like we are out of space on shared persistent volume. I will clean up the volume.
