### ISSUE TITLE
E2E tests are failing to open Podman Desktop

### ISSUE THREAD

**Issue by danivilla9** [containers/podman-desktop-e2e#261]
The latest launch of `pde2e-podman-nightly-applehv-5.2.0-dev-darwin-arm64-14.5.1` on ReportPortal (number 85) has a lot of failures that come from not being able to open Podman Desktop:
 `Error: Podman Desktop could not be started correctly with error: Error: electron.launch: Process failed to launch!`

**Comment by odockal** [comment]
It might be that at the time of the pipelines run on the machine I was connected and messed up running UI, was trying to clean up space. I will rerun machine to see if it passes now.

**Comment by odockal** [comment]
Latest runs are ok.
![Image](https://github.com/user-attachments/assets/53d0bc42-145a-4eda-8377-c06ff03ad632)
