### ISSUE TITLE
Implement/adapt E2E test case covering Podman installation via Podman Desktop on Mac

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop-e2e#63]
We need to implement or adapt e2e test case to accommodate podman installation via podman desktop on Mac environment.

**Comment by adrianriobo** [comment]
This is already covered by podman-desktop-e2e at: https://github.com/containers/podman-desktop-e2e/blob/87278c3f9ae38ed3810f8b2bcb16c02197c70dde/test/extended/podman-desktop/extension/podman/podman-extension_darwin.go#L35

We just need to provision the mac machine and set the envs on the podman-desktop-e2e container accordingly

**Comment by odockal** [comment]
@adrianriobo Great, in case nothing will need the update, we are ok to go. Just afaik, the windows installer wizard workflow differs from mac installer workflow.

**Comment by adrianriobo** [comment]
Yes yes this is why those files are per platform `_darwin` vs `_windows` both have the same `runInstaller` and depending on the platform it has its own flow

**Comment by odockal** [comment]
This works out of a box actually thanks to @adrianriobo support in goax.
