### ISSUE TITLE
Fix pdPath parameter to point to an executable file

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop-e2e#73]
PdPath points to a folder not an executable right now.

**Comment by adrianriobo** [comment]
Is this why all actions are failing?

**Comment by odockal** [comment]
@adrianriobo it fixes just Podman Desktop E2E Podman Installation step in one workflow that used locally built executable.
Job I tried to run after adjusting the pde2e-builder image: https://github.com/containers/podman-desktop-e2e/actions/runs/6948326419. The steps is now again passing. Although there are other failures, not related to this. So the fix is at place, now I need to address other problems.

**Comment by odockal** [comment]
The fix was to pass an executable path rather then folder with executable. We fixed this here, I forgot to update it in the image.

**Comment by odockal** [comment]
fixed by https://github.com/odockal/pde2e-builder/commit/ea1ca8c96e6da1e36d7fbd070cbfbf670b4e159f.
