### ISSUE TITLE
Podman Desktop E2E test Play kube yaml got stuck just after taking a screenshot of a test failure and the workflow run got stuck eventually

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop-e2e#97]
Introduce a timeout to a e2e workflows.

Investigate why the test got stuck.

Workflow run: https://github.com/containers/podman-desktop-e2e/actions/runs/7664555314/job/20889033890

**Comment by deboer-tim** [comment]
Linked logs are no longer available, but the Done button was broken and just got fixed: #8652/#8899. Is this still broken, or can we close?

**Comment by odockal** [comment]
@deboer-tim I have not seen the problem for some time. I am gonna close it.
